config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    concern :positionable do
      collection do
        post :update_positions
      end
    end
    resources :question_categories, :questions, concerns: :positionable
  end
  get 'faq', to: 'faqs#index'
end

app/models/spree/question.rb
module Spree
  class Question < ActiveRecord::Base
    acts_as_list

    translates :question, :answer,
               fallbacks_for_empty_translations: true


    include SpreeI18n::Translatable


    belongs_to :question_category, touch: true, inverse_of: :questions

    validates :question_category_id, :question, :answer, presence: true
    validates :question, uniqueness: {
      scope: :question_category,
      case_sensitive: false
    }

    delegate :name, to: :question_category, prefix: true, allow_nil: true

    default_scope { order(position: :asc) }
  end
end

app/models/spree/question_category.rb
module Spree
  class QuestionCategory < ActiveRecord::Base

    translates :name,
               fallbacks_for_empty_translations: true

    friendly_id :slug_candidates, use: [:history, :globalize]

    include SpreeI18n::Translatable

    acts_as_list

    has_many :questions, -> { order(:position) }, dependent: :destroy, inverse_of: :question_category

    validates :name, presence: true
    validates :name, uniqueness: { case_sensitive: false }

    default_scope { order(position: :asc) }
  end
end

app/controllers/spree/admin/question_categories_controller.rb
module Spree
  module Admin
    class QuestionCategoriesController < ResourceController
      before_action :question_category, only: [:new, :edit]

      def index
        @question_categories = collection
      end

      private

      def collection
        params[:q] ||= {}
        @search = Spree::QuestionCategory.ransack(params[:q])
        @collection = @search.result.includes([:questions]).page(params[:page]).per(params[:per_page])
      end

      def question_category
        @question_category ||= @object
      end

      def safe_params
        [
          :name
        ]
      end

      def question_category_params
        params.require(:question_category).permit(*safe_params)
      end
    end
  end
end

app/controllers/spree/admin/questions_controller.rb
module Spree
  module Admin
    class QuestionsController < ResourceController
      before_action :question, only: [:new, :edit]

      def index
        @questions = collection
      end

      private

      def collection
        params[:q] ||= {}
        @search = Spree::Question.ransack(params[:q])
        @collection = @search.result.includes([:question_category]).page(params[:page]).per(params[:per_page])
      end

      def question
        @question ||= @object
      end

      def safe_params
        [
          :question_category_id,
          :question,
          :answer
        ]
      end

      def question_params
        params.require(:question).permit(*safe_params)
      end
    end
  end
end

app/controllers/spree/faqs_controller.rb
module Spree
  class FaqsController < StoreController
    helper 'spree/products'

    def index
      @categories = Spree::QuestionCategory.includes(:questions).load
    end

    def default_title
      Spree.t(:frequently_asked_questions, scope: :spree_faq)
    end
  end
end

app/views/spree/admin/question_categories/_form.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: Spree::QuestionCategory.model_name.human(count: :many)), spree.admin_question_categories_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= form_for [:admin, resource] do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :name, Spree::QuestionCategory.human_attribute_name(:name) %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/question_categories/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::QuestionCategory.model_name.human) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:add_question, scope: :spree_faq), spree.new_admin_question_path, icon: 'add', class: 'btn-success', id: 'new_question_link' %>
<% end %>

<%= render 'form', resource: @question_category %>

app/views/spree/admin/question_categories/index.html.erb
<% content_for :page_title do %>
  <%= Spree::QuestionCategory.model_name.human(count: :many) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_question_category), new_admin_question_category_path, icon: 'add', class: 'btn btn-success', id: 'admin_new_question_category_link' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_question_category_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree::QuestionCategory.human_attribute_name(:name) %>
            <%= f.text_field :name_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <!-- free space -->
          </div>
        </div>
      </div>
      <div class="form-actions" data-hook="admin_question_category_index_search_buttons">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @question_categories %>

<% if @question_categories.any? %>
  <table class="table" id="listing_question_categories">
    <thead>
      <tr data-hook="admin_question_category_index_headers">
        <th><%= sort_link @search, :updated_at, Spree::QuestionCategory.human_attribute_name(:updated_at) %></th>
        <th><%= sort_link @search, :name, Spree::QuestionCategory.human_attribute_name(:name) %></th>
        <th class="text-center"><%= Spree::Question.model_name.human(count: :many) %></th>
        <th data-hook="admin_question_category_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @question_categories.each do |category| %>
        <tr id="<%= spree_dom_id category %>" data-hook="admin_question_category_index_rows" class="<%= cycle('odd', 'even') %>">
          <td><%= l category.updated_at, format: :short %></td>
          <td><%= h category.name %></td>
          <td class="text-center"><%= category.questions.try(:count) || 0 %></td>
          <td data-hook="admin_question_category_index_row_actions" class="actions text-right">
            <%= link_to_edit category, no_text: true %>
            <%= link_to_delete category, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::QuestionCategory.model_name.human(count: :many)) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_question_category_path %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @question_categories %>

app/views/spree/admin/question_categories/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_question_category) %>
<% end %>

<%= render 'form', resource: @question_category %>

app/views/spree/admin/questions/_form.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: Spree::Question.model_name.human(count: :many)), spree.admin_questions_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= form_for [:admin, resource] do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= label_tag :question_category, Spree::QuestionCategory.model_name.human %>
        <%= f.collection_select :question_category_id, Spree::QuestionCategory.reorder(name: :asc), :id, :name, { include_blank: Spree.t('match_choices.none') }, class: 'select2' %>
      </div>
      <div class="form-group">
        <%= f.label :question, Spree::Question.human_attribute_name(:question) %>
        <%= f.text_field :question, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :answer, Spree::Question.human_attribute_name(:answer) %>
        <%= f.text_area :answer, rows: 6, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/questions/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Question.model_name.human) %>
<% end %>

<%= render 'form', resource: @question %>

app/views/spree/admin/questions/index.html.erb
<% content_for :page_title do %>
  <%= Spree::Question.model_name.human(count: :many) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_question), new_object_url, icon: 'add', class: 'btn-success', id: 'admin_new_question_link' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_reviews_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_question_cont, Spree::Question.human_attribute_name(:question) %>
            <%= f.text_field :question_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_answer_cont, Spree::Question.human_attribute_name(:answer) %>
            <%= f.text_field :answer_cont, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_question_category_id_eq, Spree::QuestionCategory.model_name.human %>
            <%= f.collection_select :question_category_id_eq, Spree::QuestionCategory.all, :id, :name, { include_blank: Spree.t('match_choices.all') }, class: 'select2' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <!-- free space -->
          </div>
        </div>
      </div>
      <div class="form-actions" data-hook="admin_reviews_index_search_buttons">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @questions %>

<% if @questions.any? %>
  <table class="table sortable" id="listing_questions" data-hook data-sortable-link="<%= update_positions_admin_questions_url %>">
    <thead>
      <tr data-hook="admin_question_index_headers">
        <th class="no-border"></th>
        <th><%= sort_link @search, :updated_at, Spree::Question.human_attribute_name(:updated_at) %></th>
        <th><%= sort_link @search, :question, Spree::Question.human_attribute_name(:question) %></th>
        <th><%= sort_link @search, :question_category_id, Spree::QuestionCategory.model_name.human %></th>
        <th data-hook="admin_question_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr id="<%= spree_dom_id question %>" data-hook="admin_question_index_rows" class="<%= cycle('odd', 'even') %>">
          <td class="handle move-handle"><span class="icon icon-move handle"></span></td>
          <td><%= l question.updated_at, format: :short %></td>
          <td><%= h question.question %></td>
          <td><%= question.question_category_name %></td>
          <td data-hook="admin_question_index_row_actions" class="actions text-right">
            <%= link_to_edit question, no_text: true %>
            <%= link_to_delete question, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::Question.model_name.human(count: :many)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @questions %>

app/views/spree/admin/questions/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_question) %>
<% end %>

<%= render 'form', resource: @question %>

app/views/spree/admin/shared/_faq_main_menu.html.erb
<% if can? :admin, Spree::QuestionCategory %>
  <ul class="nav nav-sidebar">
    <%= main_menu_tree Spree.t(:faq, scope: :spree_faq), icon: 'book', sub_menu: 'faq', url: '#sidebar-faq' %>
  </ul>
<% end %>

app/views/spree/admin/shared/sub_menu/_faq.html.erb
<ul id="sidebar-faq" class="collapse nav nav-pills nav-stacked" data-hook="admin_faq_sub_tabs">
  <%= tab :questions, label: Spree.t(:questions, scope: :spree_faq) %>
  <%= tab :question_categories, label: Spree.t(:question_categories, scope: :spree_faq) %>
</ul>

app/views/spree/faqs/index.html.erb
<h1><%= Spree.t(:frequently_asked_questions, scope: :spree_faq) %></h1>

<% content_for :sidebar do %>
  <div class="affix faq-sidebar" role="complementary" data-hook="faq_sidebar">
    <h3><%= Spree.t(:faq_categories, scope: :spree_faq) %></h3>
    <ul class="nav">
    <% @categories.each do |category| %>
      <% next unless category.questions.any? %>
      <% cache(category, 'nav') do %>
        <li>
          <a href="#<%= category.name.to_url %>">
            <%= h category.name %>
          </a>
        </li>
      <% end %>
    <% end %>
  </div>
<% end if @categories.any? %>

<section id="faqs" data-hook="faq_list">
  <% @categories.each do |category| %>
    <% next unless category.questions.any? %>
    <% cache(category) do %>
      <div class="category">
        <h3 id="<%= category.name.to_url %>"><%= h category.name %></h3>
        <ul class="answers">
          <% category.questions.each do |question| %>
            <% cache(question) do %>
              <li>
                <h4><%= question.question.to_s.html_safe %></h4>
                <div class="answer">
                  <%= question.answer.to_s.html_safe %>
                </div>
                <div class="interaction">
                  <!-- for up/down votes, date, share links etc -->
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</section>